/**
 * Fetch the latest GitHub Release for oh-my-hf/ohmyhf and write download URLs.
 *
 * Usage: node scripts/fetch-release.mjs
 * Runs automatically before `astro build` via the `prebuild` script.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO = 'oh-my-hf/ohmyhf';
const API = `https://api.github.com/repos/${REPO}/releases/latest`;

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, '..', 'src', 'generated', 'release.ts');

/**
 * @param {string} name
 * @param {RegExp[]} patterns
 */
function pick(assets, patterns) {
  for (const re of patterns) {
    const hit = assets.find((a) => re.test(a.name));
    if (hit) return hit.browser_download_url;
  }
  return null;
}

const res = await fetch(API, {
  headers: {
    Accept: 'application/vnd.github+json',
    'User-Agent': 'ohmyhf-website-release-fetch',
  },
});

if (!res.ok) {
  throw new Error(`GitHub API ${res.status}: ${await res.text()}`);
}

/** @type {{ tag_name: string; html_url: string; assets: { name: string; browser_download_url: string }[] }} */
const release = await res.json();
const assets = release.assets ?? [];
const tag = release.tag_name.replace(/^v/, '');

const macOS = pick(assets, [/-arm64\.dmg$/i, /\.dmg$/i]);
const windows = pick(assets, [/Setup-.*\.exe$/i, /\.exe$/i]);
const linuxAppImage = pick(assets, [/\.AppImage$/i]);
const linuxDeb = pick(assets, [/\.deb$/i]);

const missing = [
  ['macOS', macOS],
  ['windows', windows],
  ['linuxAppImage', linuxAppImage],
  ['linuxDeb', linuxDeb],
].filter(([, url]) => !url);

if (missing.length) {
  throw new Error(
    `Missing assets on ${release.tag_name}: ${missing.map(([k]) => k).join(', ')}`,
  );
}

const source = `/* Auto-generated by scripts/fetch-release.mjs — do not edit. */
export const REPO_URL = 'https://github.com/${REPO}' as const;
export const RELEASES_URL = '${release.html_url}' as const;
export const version = '${tag}' as const;
export const released = true as const;

export const DOWNLOAD_URLS = {
  macOS: '${macOS}',
  windows: '${windows}',
  linuxAppImage: '${linuxAppImage}',
  linuxDeb: '${linuxDeb}',
} as const;
`;

writeFileSync(outPath, source);
console.log(
  `Wrote ${outPath} (${release.tag_name}: macOS/windows/linux AppImage+deb)`,
);
